### PR TITLE
Migration to Buildkite

### PR DESCRIPTION
**Pull request by leo-ri**
## What does this PR do?
Migration to Buildkite from Jenkins

### CODE REVIEW

**Comment by leo-ri** [comment]
buildkite test it

**Comment by jlind23** [comment]
Buildkite test it

**Comment by leo-ri** [comment]
buildkite test it

**Comment by leo-ri** [comment]
buildkite test it

**Comment by leo-ri** [comment]
buildkite test it

**Comment by leo-ri** [comment]
buildkite test it

**Comment by leo-ri** [comment]
buildkite test it

**Comment by leo-ri** [comment]
buildkite test it

**Comment by leo-ri** [comment]
buildkite test it

**Comment by leo-ri** [comment]
buildkite test it

**Review by mrodm — COMMENTED** [review]
Missing to add the needed environment variable to post github comments, required to update catalog-info.yml file to add ELASTIC_PR_COMMENTS_ENABLED env. Example: https://github.com/elastic/elastic-package/blob/103eb96af7dd71fd773f5588ab85c6f4b5603bdb/catalog-info.yaml#L56-L57

In Jenkins, it was done [here](https://github.com/elastic/elastic-agent-inputs/blob/d5127b32430900dbeddb04051124928805d1e2bc/.ci/Jenkinsfile#L85)

**Comment by mrodm** [comment]
@leo-ri it looks like that the new Buildkite pipeline is not executed now. cc @jlind23 
Maybe something related to the webhook ?

**Review by mrodm — APPROVED** [review]
LGTM

Just add some comment about why it was needed that `awk` command in the test step.

**Review by mrodm — APPROVED** [review]

**Pull request merged**
